name: samples
description: "Samples for the Abelliz Widgets"
publish_to: "none"
version: 1.0.1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  abelliz_essentials:
    path: "../"

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
